services:
  frontend: 
    image: derekortiz/hc-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NEXT_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  frontend-data: